### ISSUE TITLE
[Bug] Request Failed with Status 500

### ISSUE THREAD

**Issue by ayush-that** [Avocodos/avocodos#2]
**Description**: When I tried to post my first post on the platform, the request failed with a 500 Internal Server Error. This issue occurred when I included an emoji in the post text field.

I have not been able to reproduce the issue after the initial occurrence.
Other functionalities, such as posting without emojis, commenting, liking, and account creation, are working as expected.

![image](https://github.com/user-attachments/assets/777618ca-7f7d-4ed5-826d-21d67d59c55a)

**Comment by HarjjotSinghh** [comment]
This could have occurred if you maybe tried to send the post multiple times/clicked on the submit button multiple times. It also could just be the uploadthing server not working randomly for some reason.

I just tried creating 2 posts, both with emojis, one with files and one without files, and it works just fine. 

Let me know if this error occurs again but I doubt that will be the case.

Thanks for raising an issue!

**Comment by HarjjotSinghh** [comment]
I am closing this issue now. @ayush-that please re-open this issue if something similar to this occurs again.
