### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by RG1208** [Avocodos/avocodos#5]
I recenty noticed some bugs that can be fixed.

1. While scrolling down the "Trending Topics" bar should also scroll down so that we can see all the trending topics.It only moves down when we reach to the bottom of the page
2. In the mobile view, the footer is not showing properly.

https://github.com/user-attachments/assets/2bd32505-f7f0-47d6-8945-e8bb3e4dcd34

![Footer](https://github.com/user-attachments/assets/9f7e80dd-7f45-428a-af15-91b3275b17b7)

**Comment by HarjjotSinghh** [comment]
Hey @RG1208, thanks for raising an issue. I will see if I can find any solution for the "Trending Topics" card getting out of viewport. Is there any solution you can propose to fix the same? I was thinking to maybe merge the 2 cards (Who To Follow and Trending Topics) and convert them into a single "scrollable" component. What are your thoughts on the same?

And as for the mobile navbar overflow issue, that has a pretty straight-forward fix and I will implement the same by tomorrow.

Thanks once again for the issue.

**Comment by RG1208** [comment]
The navbar overflow issue has been resolved and yes you can create one single scrollbar for both the "trending topic" and "who to follow". I think that will work
